sudo: false
language: java

services:
  - mongodb

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

before_install:
  - export TZ=Asia/Shanghai

after_success:
  - bash <(curl -s https://codecov.io/bash)
